name: Continuous Integration

on:
  pull_request:
    branches:
      - "main"

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.3"

      # TODO: If we need SSH agent, need repo admin to add secret key
      # - name: Setup SSH Agent
      #   uses: webfactory/ssh-agent@v0.5.2
      #   with:
      #     ssh-private-key: ${{ secrets.SSH_KEY}}

      - name: Upgrade pip
        run: uv pip install --system --upgrade pip

      - name: Install dependencies
        run: uv pip install --system -vv ".[dev]"

      - name: Lint with Flake8
        run: python -m flake8 .

      - name: Setup mock env
        run: echo "WORKING_DIR='./'" >> "$GITHUB_ENV"

      - name: Test with pytest
        run: python -m pytest tests -vs

      - name: Formatter check with black
        run: python -m black --check .
